# Generated by Django 5.0.1 on 2024-01-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
